<?php if (Mage::getStoreConfig('easybanner/info/enabled')):?>
<script src="<?php echo $this->getSkinUrl('js/easybanner/jquery.msAccordion.js')?>" type="text/javascript"></script>
<?php if ($this->isVisible()): ?>
<?php $_banner = $this->getBanner(); ?>
<?php if ($_banner->getShowTitle()==1): ?>
<h3><?php echo $_banner->getTitle(); ?></h3>
<?php endif; ?>

<div class="banner-top">
	<div class="accordionWrapper" id="accordion1">		
		<?php $_banner_items = $this->getBannerItems(); ?>
			<?php $i=1; foreach ($_banner_items as $_banner_item): ?>
				<div class="set set1">
					<div class="title"><img src=<?php echo $this->getSkinUrl('images/accordion_slider/menu'.$i.'-h.jpg') ?> width="35px" height="249" alt="easybanner" /></div>					
					<div class="content">
					<a href="<?php echo $_banner_item->getLinkUrl(); ?>"> 
						<?php if ($_banner_item->getImage()): ?>
							<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$_banner_item->getImage()?>" width="<?php echo $_banner->getWidth().'px'?> " height=" <?php echo $_banner->getHeight().'px'?>" alt="easybanner"/>
						<?php elseif ($_banner_item->getImageUrl()): ?>
							<img src="<?php echo $_banner_item->getImageUrl() ?>" width="<?php echo $_banner->getWidth().'px'?> " height=" <?php echo $_banner->getHeight().'px'?>" alt="easybanner" />
						<?php endif; ?>
					</a>
					</div>				
				</div>
				<?php $i++ ?>
			<?php endforeach ?>
	</div>
</div>	
<?php endif; ?>	
<script type="text/javascript">
	jQuery.noConflict(); 
	jQuery(document).ready(function(){	
		jQuery("#accordion1").msAccordion({defaultid:0, autodelay:1});
	});	
</script>

<?php endif;?>
